
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
shell_command:
    play_local_notification: 'ffplay -nodisp -vn /config/www/test.wav'
media_player:
  - platform: command_line
    name: RPi Audio
    command: aplay -q "{{media_content_id}}"
browser_mod:
  prefix: "browser"
logger:
  default: warning
  logs:
    homeassistant.components.conversation: debug
    homeassistant.components.assist_pipeline: debug
